version: 2

project_name: pod-rightsizer

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: pod-rightsizer
    main: ./cmd/pod-rightsizer
    binary: pod-rightsizer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

  - id: advisor-api
    main: ./cmd/advisor-api
    binary: advisor-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: default
    ids:
      - pod-rightsizer
      - advisor-api
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  prerelease: auto
